2021-12-11 21:48:47,351 ERROR: Exception on /login [GET] [in /Users/alex/Developer/timetableSystem/venv/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/Users/alex/Developer/timetableSystem/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/alex/Developer/timetableSystem/venv/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/alex/Developer/timetableSystem/venv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/alex/Developer/timetableSystem/venv/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/alex/Developer/timetableSystem/app/routes.py", line 35, in login
    return render_template('login.html', title='Sign In', form=form)
  File "/Users/alex/Developer/timetableSystem/venv/lib/python3.9/site-packages/flask/templating.py", line 148, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/alex/Developer/timetableSystem/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1068, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/alex/Developer/timetableSystem/venv/lib/python3.9/site-packages/jinja2/environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "/Users/alex/Developer/timetableSystem/venv/lib/python3.9/site-packages/jinja2/environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/Users/alex/Developer/timetableSystem/venv/lib/python3.9/site-packages/jinja2/loaders.py", line 137, in load
    code = environment.compile(source, name, filename)
  File "/Users/alex/Developer/timetableSystem/venv/lib/python3.9/site-packages/jinja2/environment.py", line 757, in compile
    self.handle_exception(source=source_hint)
  File "/Users/alex/Developer/timetableSystem/venv/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/alex/Developer/timetableSystem/app/templates/login.html", line 4, in template
    <img src="{{ url_for('static', filename='train.jpg' }}" alt="Train">
jinja2.exceptions.TemplateSyntaxError: unexpected '}', expected ')'
2021-12-11 21:48:51,737 ERROR: Exception on /login [GET] [in /Users/alex/Developer/timetableSystem/venv/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/Users/alex/Developer/timetableSystem/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/alex/Developer/timetableSystem/venv/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/alex/Developer/timetableSystem/venv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/alex/Developer/timetableSystem/venv/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/alex/Developer/timetableSystem/app/routes.py", line 35, in login
    return render_template('login.html', title='Sign In', form=form)
  File "/Users/alex/Developer/timetableSystem/venv/lib/python3.9/site-packages/flask/templating.py", line 148, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/alex/Developer/timetableSystem/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1068, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/alex/Developer/timetableSystem/venv/lib/python3.9/site-packages/jinja2/environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "/Users/alex/Developer/timetableSystem/venv/lib/python3.9/site-packages/jinja2/environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/Users/alex/Developer/timetableSystem/venv/lib/python3.9/site-packages/jinja2/loaders.py", line 137, in load
    code = environment.compile(source, name, filename)
  File "/Users/alex/Developer/timetableSystem/venv/lib/python3.9/site-packages/jinja2/environment.py", line 757, in compile
    self.handle_exception(source=source_hint)
  File "/Users/alex/Developer/timetableSystem/venv/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/alex/Developer/timetableSystem/app/templates/login.html", line 4, in template
    <img src="{{ url_for('static', filename='train.jpg' }}" alt="Train">
jinja2.exceptions.TemplateSyntaxError: unexpected '}', expected ')'
2021-12-11 21:48:53,470 ERROR: Exception on /login [GET] [in /Users/alex/Developer/timetableSystem/venv/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/Users/alex/Developer/timetableSystem/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/alex/Developer/timetableSystem/venv/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/alex/Developer/timetableSystem/venv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/alex/Developer/timetableSystem/venv/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/alex/Developer/timetableSystem/app/routes.py", line 35, in login
    return render_template('login.html', title='Sign In', form=form)
  File "/Users/alex/Developer/timetableSystem/venv/lib/python3.9/site-packages/flask/templating.py", line 148, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/alex/Developer/timetableSystem/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1068, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/alex/Developer/timetableSystem/venv/lib/python3.9/site-packages/jinja2/environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "/Users/alex/Developer/timetableSystem/venv/lib/python3.9/site-packages/jinja2/environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/Users/alex/Developer/timetableSystem/venv/lib/python3.9/site-packages/jinja2/loaders.py", line 137, in load
    code = environment.compile(source, name, filename)
  File "/Users/alex/Developer/timetableSystem/venv/lib/python3.9/site-packages/jinja2/environment.py", line 757, in compile
    self.handle_exception(source=source_hint)
  File "/Users/alex/Developer/timetableSystem/venv/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/alex/Developer/timetableSystem/app/templates/login.html", line 4, in template
    <img src="{{ url_for('static', filename='train.jpg' }}" alt="Train">
jinja2.exceptions.TemplateSyntaxError: unexpected '}', expected ')'
2021-12-11 21:49:09,641 INFO: Microblog startup [in /Users/alex/Developer/timetableSystem/app/__init__.py:52]
2021-12-11 21:55:43,228 INFO: Microblog startup [in /Users/alex/Developer/timetableSystem/app/__init__.py:52]
2021-12-11 21:56:06,457 INFO: Microblog startup [in /Users/alex/Developer/timetableSystem/app/__init__.py:52]
2021-12-11 21:56:25,875 INFO: Microblog startup [in /Users/alex/Developer/timetableSystem/app/__init__.py:52]
