2021-12-11 20:01:05,377 ERROR: Exception on /logout [GET] [in /Users/alex/Developer/timetableSystem/venv/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/Users/alex/Developer/timetableSystem/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/alex/Developer/timetableSystem/venv/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/alex/Developer/timetableSystem/venv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/alex/Developer/timetableSystem/venv/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/alex/Developer/timetableSystem/app/routes.py", line 41, in logout
    return redirect(url_for('index'))
  File "/Users/alex/Developer/timetableSystem/venv/lib/python3.9/site-packages/flask/helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Users/alex/Developer/timetableSystem/venv/lib/python3.9/site-packages/flask/helpers.py", line 325, in url_for
    rv = url_adapter.build(
  File "/Users/alex/Developer/timetableSystem/venv/lib/python3.9/site-packages/werkzeug/routing.py", line 2314, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'index'. Did you mean 'login' instead?
2021-12-11 20:01:06,501 ERROR: Exception on /logout [GET] [in /Users/alex/Developer/timetableSystem/venv/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/Users/alex/Developer/timetableSystem/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/alex/Developer/timetableSystem/venv/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/alex/Developer/timetableSystem/venv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/alex/Developer/timetableSystem/venv/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/alex/Developer/timetableSystem/app/routes.py", line 41, in logout
    return redirect(url_for('index'))
  File "/Users/alex/Developer/timetableSystem/venv/lib/python3.9/site-packages/flask/helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Users/alex/Developer/timetableSystem/venv/lib/python3.9/site-packages/flask/helpers.py", line 325, in url_for
    rv = url_adapter.build(
  File "/Users/alex/Developer/timetableSystem/venv/lib/python3.9/site-packages/werkzeug/routing.py", line 2314, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'index'. Did you mean 'login' instead?
2021-12-11 20:02:25,579 INFO: Microblog startup [in /Users/alex/Developer/timetableSystem/app/__init__.py:50]
2021-12-11 20:02:29,033 ERROR: Exception on /login [GET] [in /Users/alex/Developer/timetableSystem/venv/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/Users/alex/Developer/timetableSystem/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/alex/Developer/timetableSystem/venv/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/alex/Developer/timetableSystem/venv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/alex/Developer/timetableSystem/venv/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/alex/Developer/timetableSystem/app/routes.py", line 35, in login
    return render_template('login.html', title='Sign In', form=form)
  File "/Users/alex/Developer/timetableSystem/venv/lib/python3.9/site-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/Users/alex/Developer/timetableSystem/venv/lib/python3.9/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/Users/alex/Developer/timetableSystem/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/Users/alex/Developer/timetableSystem/venv/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/alex/Developer/timetableSystem/app/templates/login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/alex/Developer/timetableSystem/app/templates/base.html", line 26, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/alex/Developer/timetableSystem/app/templates/login.html", line 8, in block 'content'
    {{ form.username.label }}<br>
  File "/Users/alex/Developer/timetableSystem/venv/lib/python3.9/site-packages/jinja2/environment.py", line 474, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'app.forms.LoginForm object' has no attribute 'username'
2021-12-11 20:02:56,525 INFO: Microblog startup [in /Users/alex/Developer/timetableSystem/app/__init__.py:50]
2021-12-11 20:02:57,417 ERROR: Exception on /login [GET] [in /Users/alex/Developer/timetableSystem/venv/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/Users/alex/Developer/timetableSystem/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/alex/Developer/timetableSystem/venv/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/alex/Developer/timetableSystem/venv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/alex/Developer/timetableSystem/venv/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/alex/Developer/timetableSystem/app/routes.py", line 35, in login
    return render_template('login.html', title='Sign In', form=form)
  File "/Users/alex/Developer/timetableSystem/venv/lib/python3.9/site-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/Users/alex/Developer/timetableSystem/venv/lib/python3.9/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/Users/alex/Developer/timetableSystem/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/Users/alex/Developer/timetableSystem/venv/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/alex/Developer/timetableSystem/app/templates/login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/alex/Developer/timetableSystem/app/templates/base.html", line 26, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/alex/Developer/timetableSystem/app/templates/login.html", line 8, in block 'content'
    {{ form.username.label }}<br>
  File "/Users/alex/Developer/timetableSystem/venv/lib/python3.9/site-packages/jinja2/environment.py", line 474, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'app.forms.LoginForm object' has no attribute 'username'
